package com.example.propertymanagement.datasource

import com.example.propertymanagement.R
import com.example.propertymanagement.model.Seller
import com.example.propertymanagement.model.PropertyUnit
import com.example.propertymanagement.model.UnitImage
import com.example.propertymanagement.ui.views.ListingsType

object Datasource {
    val bedsitters = listOf<UnitImage>(
        UnitImage(
            1,
            R.drawable.bedsitter1
        ),
        UnitImage(
            2,
            R.drawable.bedsitter2
        ),
        UnitImage(
            3,
            R.drawable.bedsitter3
        ),
        UnitImage(
            4,
            R.drawable.bedsitter4
        ),
        UnitImage(
            5,
            R.drawable.bedsitter5
        ),
    )

    val oneBedrooms = listOf<UnitImage>(
        UnitImage(
            1,
            R.drawable._bedroom1
        ),
        UnitImage(
            2,
            R.drawable._bedroom2
        ),
        UnitImage(
            3,
            R.drawable._bedroom3
        )
    )

    val units = listOf<PropertyUnit>(
        PropertyUnit(
            1,
            R.string.spacious_bedsitter,
            ListingsType.RENTALS,
            R.string.bedsitter_description,
            R.string.nairobi,
            bedsitters,
            Seller(
                1,
                "Alex",
                "0794649026"
            )
        ),
        PropertyUnit(
            2,
            R.string.spacious_bedsitter,
            ListingsType.AIRBNB,
            R.string.bedsitter_description,
            R.string.nairobi,
            bedsitters,
            Seller(
                2,
                "John",
                "0794649027"
            )
        ),
        PropertyUnit(
            3,
            R.string.spacious_bedsitter,
            ListingsType.RENTALS,
            R.string.bedsitter_description,
            R.string.nairobi,
            bedsitters,
            Seller(
                3,
                "Felix",
                "0894649026"
            )
        ),
        PropertyUnit(
            4,
            R.string.spacious_bedsitter,
            ListingsType.AIRBNB,
            R.string.bedsitter_description,
            R.string.nakuru,
            bedsitters,
            Seller(
                4,
                "Jane",
                "0774649054"
            )
        ),
        PropertyUnit(
            5,
            R.string.spacious_bedsitter,
            ListingsType.RENTALS,
            R.string.bedsitter_description,
            R.string.nakuru,
            bedsitters,
            Seller(
                5,
                "Alice",
                "0784649054"
            )
        ),
        PropertyUnit(
            6,
            R.string.one_bedroom,
            ListingsType.AIRBNB,
            R.string.one_bedroom_description,
            R.string.nairobi,
            oneBedrooms,
            Seller(
                6,
                "Alex",
                "0774649054"
            )
        ),
        PropertyUnit(
            7,
            R.string.one_bedroom,
            ListingsType.RENTALS,
            R.string.one_bedroom_description,
            R.string.nairobi,
            oneBedrooms,
            Seller(
                7,
                "Alex",
                "0774649054"
            )
        ),
        PropertyUnit(
            8,
            R.string.one_bedroom,
            ListingsType.AIRBNB,
            R.string.one_bedroom_description,
            R.string.nakuru,
            oneBedrooms,
            Seller(
                8,
                "Alex",
                "0774649054"
            )
        ),
    )
}